export enum ValidTagsEnum {
  Hightlight0 = 'hightlight-0',
  Hightlight1 = 'hightlight-1',
  Hightlight2 = 'hightlight-2',
  Hightlight3 = 'hightlight-3',
  Hightlight4 = 'hightlight-4',
  Hightlight5 = 'hightlight-5',
  Hightlight6 = 'hightlight-6',
  Hightlight7 = 'hightlight-7',
  Hightlight8 = 'hightlight-8',
  Hightlight9 = 'hightlight-9',
  HightlightA = 'hightlight-a',
  HightlightB = 'hightlight-b',
  HightlightC = 'hightlight-c',
  HightlightD = 'hightlight-d',
  HightlightE = 'hightlight-e',
  HightlightF = 'hightlight-f',
  HightlightG = 'hightlight-g',
}

export enum TagNamesEnum {
  Hightlight0 = 'Contraste',
  Hightlight1 = 'Dios',
  Hightlight2 = 'Jesucristo',
  Hightlight3 = 'Pregunta',
  Hightlight4 = 'Personas',
  Hightlight5 = 'Destinatarios',
  Hightlight6 = 'Lugares',
  Hightlight7 = 'Tiempo',
  Hightlight8 = 'Palabra Clave',
  Hightlight9 = 'Palabra repetida',
  HightlightA = 'Propósito',
  HightlightB = 'Razón',
  HightlightC = 'Razón',
  HightlightD = 'Conclusión',
  HightlightE = 'Verbo pasivo',
  HightlightF = 'Verbo activo',
  HightlightG = 'Causa-efecto',
}
